// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0K6w0cRTucY8TBp6qt1hJccCyZoW-nZ8',
    appId: '1:917634580416:web:13f5900fd0950ad79f1225',
    messagingSenderId: '917634580416',
    projectId: 'flash-chat-3efcb',
    authDomain: 'flash-chat-3efcb.firebaseapp.com',
    storageBucket: 'flash-chat-3efcb.appspot.com',
    measurementId: 'G-CQVQQVVEBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTw3W4R4ZbODnh4CjUFikS27YcHmVChsA',
    appId: '1:917634580416:android:7761e0c419248a499f1225',
    messagingSenderId: '917634580416',
    projectId: 'flash-chat-3efcb',
    storageBucket: 'flash-chat-3efcb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFAgqrhV5BVihKOoLDVl3S2y9i2abn5_I',
    appId: '1:917634580416:ios:60a41da538ae5fcf9f1225',
    messagingSenderId: '917634580416',
    projectId: 'flash-chat-3efcb',
    storageBucket: 'flash-chat-3efcb.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFAgqrhV5BVihKOoLDVl3S2y9i2abn5_I',
    appId: '1:917634580416:ios:60a41da538ae5fcf9f1225',
    messagingSenderId: '917634580416',
    projectId: 'flash-chat-3efcb',
    storageBucket: 'flash-chat-3efcb.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0K6w0cRTucY8TBp6qt1hJccCyZoW-nZ8',
    appId: '1:917634580416:web:2b8fc959433b82049f1225',
    messagingSenderId: '917634580416',
    projectId: 'flash-chat-3efcb',
    authDomain: 'flash-chat-3efcb.firebaseapp.com',
    storageBucket: 'flash-chat-3efcb.appspot.com',
    measurementId: 'G-SJ9SZV1LH4',
  );
}
